<?php
$sql = "CREATE TABLE IF NOT EXISTS `user` (
  `auid` bigint NOT NULL AUTO_INCREMENT,
  `puid` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `suid` char(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tuid` char(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `luid` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entry` enum('ORIGIN','FIXED','STATIC') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ORIGIN',
  `author` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ORIGIN',
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `oauthid` char(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nin` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mid` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `username` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nick` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firstname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `middlename` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `gender` enum('F','M') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relationship` enum('SINGLE','PARTNERSHIP','MARRIED','DIVORCED','SEPARATED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nationality` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bio` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dp` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cp` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sign` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `religion` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `occupation` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `family` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vip` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `corporate` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `living` json DEFAULT NULL,
  `origin` json DEFAULT NULL,
  `hmo` json DEFAULT NULL,
  `medical` json DEFAULT NULL,
  `contact` json DEFAULT NULL,
  `guardian` json DEFAULT NULL,
  `nok` json DEFAULT NULL,
  `verified` json DEFAULT NULL,
  `otp` json DEFAULT NULL,
  `saas` json DEFAULT NULL,
  `group` set('INDIVIDUAL','FAMILY','VIP','CORPORATE','HMO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `department` set('PATIENT','RECEPTION','NURSE','DOCTOR','RADIOLOGY','LABORATORY','ACCOUNTANT','CASHIER','PHARMACY','HR','ADMIN') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is` enum('DOCTOR','NURSE','PROFESSIONAL','ADMINISTRATIVE') COLLATE utf8mb4_unicode_ci DEFAULT 'PROFESSIONAL',
  `type` enum('MASTER','ADMIN','MANAGER','SUPERVISOR','STANDARD','BASIC') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'BASIC',
  `flag` enum('NORMAL','PASSWORD_CHANGED','PASSWORD_CHANGE_REQUIRED','PASSWORD_TEMPORARY','PASSWORD_GENERATED','OTP') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'NORMAL',
  `status` enum('NEW','PENDING','ACTIVE','INACTIVE','BANNED','DEACTIVATED','DELETED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'NEW',
  `kind` enum('PERSON','OFFICE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'PERSON',
  `role` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `referrer` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastseen` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`auid`) USING BTREE,
  UNIQUE KEY `puid` (`puid`) USING BTREE,
  UNIQUE KEY `suid` (`suid`) USING BTREE,
  UNIQUE KEY `tuid` (`tuid`) USING BTREE,
  UNIQUE KEY `oauthid` (`oauthid`) USING BTREE,
  UNIQUE KEY `email` (`email`) USING BTREE,
  UNIQUE KEY `phone` (`phone`) USING BTREE,
  UNIQUE KEY `username` (`username`) USING BTREE,
  UNIQUE KEY `nin` (`nin`),
  UNIQUE KEY `mid` (`mid`),
  KEY `luid` (`luid`) USING BTREE,
  KEY `created` (`created`) USING BTREE,
  KEY `updated` (`updated`) USING BTREE,
  KEY `entry` (`entry`) USING BTREE,
  KEY `author` (`author`) USING BTREE,
  KEY `password` (`password`) USING BTREE,
  KEY `lastseen` (`lastseen`) USING BTREE,
  KEY `nick` (`nick`),
  KEY `firstname` (`firstname`),
  KEY `lastname` (`lastname`),
  KEY `middlename` (`middlename`),
  KEY `dob` (`dob`),
  KEY `gender` (`gender`),
  KEY `relationship` (`relationship`),
  KEY `nationality` (`nationality`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;";
return $sql;